Add quiet mode to ahjo-scan. Abort commit if error occurs in precommit hook
DP-492

diff --git a/src/ahjo/resources/files/git_hooks/pre-commit b/src/ahjo/resources/files/git_hooks/pre-commit
--- a/src/ahjo/resources/files/git_hooks/pre-commit
+++ b/src/ahjo/resources/files/git_hooks/pre-commit
@@ -7,7 +7,7 @@ red='\033[0;31m'
 no_color='\033[0m'
 
 echo "Scanning for sensitive data..."
-ahjo-scan.exe --stage --files "^.*"
+ahjo-scan.exe --stage --files "^.*" --quiet
 exit_status=$?
 
 if [ $exit_status -eq 1 ]; then
@@ -17,6 +17,9 @@ if [ $exit_status -eq 1 ]; then
 elif [ $exit_status -eq 0 ]; then
     echo -e "${green}Scan check passed.${no_color}\n"
     exit 0
-else
-    exit 0
+else 
+    this_file_path=$(realpath $0)
+    echo "Scan check failed. Make sure ahjo is installed correctly and try again. If you want to commit without scanning, remove this hook from $this_file_path."
+    echo -e "${red}Commit aborted.${no_color}"
+    exit 1
 fi
